services:
    ponydownloader:
      container_name: ponydownloader
      ports:
        - 9999:9999 # HTTP port (host:container)
      environment:
        - PUID=0
        - PGID=0
        - UMASK=022
      volumes:
        - ~/PonyDownloader/Downloads:/app/Downloads # mount download path
        #- ~/PonyDownloader/storage:/app/storage # if you need to mount storage path, uncomment this line
      restart: unless-stopped
      image: mutantcat/ponydownloader
      # command: -u Username -p Password # optional authentication
